# Generated by Django 4.2.7 on 2024-11-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
